// Code generated by tools/gen_palettes.py from
// ratatui-core/src/style/palette/material.rs @ ratatui-v0.30.2. DO NOT EDIT.

// Package material holds Google's 2014 Material design colour palettes, as
// ratatui does.
//
// Each palette is a ramp of ten shades of one hue, from C50 at the lightest to
// C900 at the darkest. Most also carry four accent colours, A100 to A700, which
// are brighter than the ramp and meant for the one thing on screen that should
// catch the eye:
//
//	style := catatui.NewStyle().
//		Fg(material.Indigo.A200).
//		Bg(material.BlueGray.C900)
//
// These are 24-bit colours, so a terminal without true colour support will
// approximate them.
package material

import "github.com/Fiend3d/catatui"

// Palette is one hue in ten shades, lightest first.
type Palette struct {
	C50  catatui.Color
	C100 catatui.Color
	C200 catatui.Color
	C300 catatui.Color
	C400 catatui.Color
	C500 catatui.Color
	C600 catatui.Color
	C700 catatui.Color
	C800 catatui.Color
	C900 catatui.Color
}

// AccentedPalette is a Palette with four accent colours beside it.
type AccentedPalette struct {
	C50  catatui.Color
	C100 catatui.Color
	C200 catatui.Color
	C300 catatui.Color
	C400 catatui.Color
	C500 catatui.Color
	C600 catatui.Color
	C700 catatui.Color
	C800 catatui.Color
	C900 catatui.Color
	A100 catatui.Color
	A200 catatui.Color
	A400 catatui.Color
	A700 catatui.Color
}

// Black is included so that a design does not have to fall back on the
// terminal's own idea of it.
var Black = catatui.RgbFromU32(0x000000)

// White is included so that a design does not have to fall back on the
// terminal's own idea of it.
var White = catatui.RgbFromU32(0xffffff)

// Red is the red ramp, with accents.
var Red = AccentedPalette{
	C50:  catatui.RgbFromU32(0xffebee),
	C100: catatui.RgbFromU32(0xffcdd2),
	C200: catatui.RgbFromU32(0xef9a9a),
	C300: catatui.RgbFromU32(0xe57373),
	C400: catatui.RgbFromU32(0xef5350),
	C500: catatui.RgbFromU32(0xf44336),
	C600: catatui.RgbFromU32(0xe53935),
	C700: catatui.RgbFromU32(0xd32f2f),
	C800: catatui.RgbFromU32(0xc62828),
	C900: catatui.RgbFromU32(0xb71c1c),
	A100: catatui.RgbFromU32(0xff8a80),
	A200: catatui.RgbFromU32(0xff5252),
	A400: catatui.RgbFromU32(0xff1744),
	A700: catatui.RgbFromU32(0xd50000),
}

// Pink is the pink ramp, with accents.
var Pink = AccentedPalette{
	C50:  catatui.RgbFromU32(0xfce4ec),
	C100: catatui.RgbFromU32(0xf8bbd0),
	C200: catatui.RgbFromU32(0xf48fb1),
	C300: catatui.RgbFromU32(0xf06292),
	C400: catatui.RgbFromU32(0xec407a),
	C500: catatui.RgbFromU32(0xe91e63),
	C600: catatui.RgbFromU32(0xd81b60),
	C700: catatui.RgbFromU32(0xc2185b),
	C800: catatui.RgbFromU32(0xad1457),
	C900: catatui.RgbFromU32(0x880e4f),
	A100: catatui.RgbFromU32(0xff80ab),
	A200: catatui.RgbFromU32(0xff4081),
	A400: catatui.RgbFromU32(0xf50057),
	A700: catatui.RgbFromU32(0xc51162),
}

// Purple is the purple ramp, with accents.
var Purple = AccentedPalette{
	C50:  catatui.RgbFromU32(0xf3e5f5),
	C100: catatui.RgbFromU32(0xe1bee7),
	C200: catatui.RgbFromU32(0xce93d8),
	C300: catatui.RgbFromU32(0xba68c8),
	C400: catatui.RgbFromU32(0xab47bc),
	C500: catatui.RgbFromU32(0x9c27b0),
	C600: catatui.RgbFromU32(0x8e24aa),
	C700: catatui.RgbFromU32(0x7b1fa2),
	C800: catatui.RgbFromU32(0x6a1b9a),
	C900: catatui.RgbFromU32(0x4a148c),
	A100: catatui.RgbFromU32(0xea80fc),
	A200: catatui.RgbFromU32(0xe040fb),
	A400: catatui.RgbFromU32(0xd500f9),
	A700: catatui.RgbFromU32(0xaa00ff),
}

// DeepPurple is the deep purple ramp, with accents.
var DeepPurple = AccentedPalette{
	C50:  catatui.RgbFromU32(0xede7f6),
	C100: catatui.RgbFromU32(0xd1c4e9),
	C200: catatui.RgbFromU32(0xb39ddb),
	C300: catatui.RgbFromU32(0x9575cd),
	C400: catatui.RgbFromU32(0x7e57c2),
	C500: catatui.RgbFromU32(0x673ab7),
	C600: catatui.RgbFromU32(0x5e35b1),
	C700: catatui.RgbFromU32(0x512da8),
	C800: catatui.RgbFromU32(0x4527a0),
	C900: catatui.RgbFromU32(0x311b92),
	A100: catatui.RgbFromU32(0xb388ff),
	A200: catatui.RgbFromU32(0x7c4dff),
	A400: catatui.RgbFromU32(0x651fff),
	A700: catatui.RgbFromU32(0x6200ea),
}

// Indigo is the indigo ramp, with accents.
var Indigo = AccentedPalette{
	C50:  catatui.RgbFromU32(0xe8eaf6),
	C100: catatui.RgbFromU32(0xc5cae9),
	C200: catatui.RgbFromU32(0x9fa8da),
	C300: catatui.RgbFromU32(0x7986cb),
	C400: catatui.RgbFromU32(0x5c6bc0),
	C500: catatui.RgbFromU32(0x3f51b5),
	C600: catatui.RgbFromU32(0x3949ab),
	C700: catatui.RgbFromU32(0x303f9f),
	C800: catatui.RgbFromU32(0x283593),
	C900: catatui.RgbFromU32(0x1a237e),
	A100: catatui.RgbFromU32(0x8c9eff),
	A200: catatui.RgbFromU32(0x536dfe),
	A400: catatui.RgbFromU32(0x3d5afe),
	A700: catatui.RgbFromU32(0x304ffe),
}

// Blue is the blue ramp, with accents.
var Blue = AccentedPalette{
	C50:  catatui.RgbFromU32(0xe3f2fd),
	C100: catatui.RgbFromU32(0xbbdefb),
	C200: catatui.RgbFromU32(0x90caf9),
	C300: catatui.RgbFromU32(0x64b5f6),
	C400: catatui.RgbFromU32(0x42a5f5),
	C500: catatui.RgbFromU32(0x2196f3),
	C600: catatui.RgbFromU32(0x1e88e5),
	C700: catatui.RgbFromU32(0x1976d2),
	C800: catatui.RgbFromU32(0x1565c0),
	C900: catatui.RgbFromU32(0x0d47a1),
	A100: catatui.RgbFromU32(0x82b1ff),
	A200: catatui.RgbFromU32(0x448aff),
	A400: catatui.RgbFromU32(0x2979ff),
	A700: catatui.RgbFromU32(0x2962ff),
}

// LightBlue is the light blue ramp, with accents.
var LightBlue = AccentedPalette{
	C50:  catatui.RgbFromU32(0xe1f5fe),
	C100: catatui.RgbFromU32(0xb3e5fc),
	C200: catatui.RgbFromU32(0x81d4fa),
	C300: catatui.RgbFromU32(0x4fc3f7),
	C400: catatui.RgbFromU32(0x29b6f6),
	C500: catatui.RgbFromU32(0x03a9f4),
	C600: catatui.RgbFromU32(0x039be5),
	C700: catatui.RgbFromU32(0x0288d1),
	C800: catatui.RgbFromU32(0x0277bd),
	C900: catatui.RgbFromU32(0x01579b),
	A100: catatui.RgbFromU32(0x80d8ff),
	A200: catatui.RgbFromU32(0x40c4ff),
	A400: catatui.RgbFromU32(0x00b0ff),
	A700: catatui.RgbFromU32(0x0091ea),
}

// Cyan is the cyan ramp, with accents.
var Cyan = AccentedPalette{
	C50:  catatui.RgbFromU32(0xe0f7fa),
	C100: catatui.RgbFromU32(0xb2ebf2),
	C200: catatui.RgbFromU32(0x80deea),
	C300: catatui.RgbFromU32(0x4dd0e1),
	C400: catatui.RgbFromU32(0x26c6da),
	C500: catatui.RgbFromU32(0x00bcd4),
	C600: catatui.RgbFromU32(0x00acc1),
	C700: catatui.RgbFromU32(0x0097a7),
	C800: catatui.RgbFromU32(0x00838f),
	C900: catatui.RgbFromU32(0x006064),
	A100: catatui.RgbFromU32(0x84ffff),
	A200: catatui.RgbFromU32(0x18ffff),
	A400: catatui.RgbFromU32(0x00e5ff),
	A700: catatui.RgbFromU32(0x00b8d4),
}

// Teal is the teal ramp, with accents.
var Teal = AccentedPalette{
	C50:  catatui.RgbFromU32(0xe0f2f1),
	C100: catatui.RgbFromU32(0xb2dfdb),
	C200: catatui.RgbFromU32(0x80cbc4),
	C300: catatui.RgbFromU32(0x4db6ac),
	C400: catatui.RgbFromU32(0x26a69a),
	C500: catatui.RgbFromU32(0x009688),
	C600: catatui.RgbFromU32(0x00897b),
	C700: catatui.RgbFromU32(0x00796b),
	C800: catatui.RgbFromU32(0x00695c),
	C900: catatui.RgbFromU32(0x004d40),
	A100: catatui.RgbFromU32(0xa7ffeb),
	A200: catatui.RgbFromU32(0x64ffda),
	A400: catatui.RgbFromU32(0x1de9b6),
	A700: catatui.RgbFromU32(0x00bfa5),
}

// Green is the green ramp, with accents.
var Green = AccentedPalette{
	C50:  catatui.RgbFromU32(0xe8f5e9),
	C100: catatui.RgbFromU32(0xc8e6c9),
	C200: catatui.RgbFromU32(0xa5d6a7),
	C300: catatui.RgbFromU32(0x81c784),
	C400: catatui.RgbFromU32(0x66bb6a),
	C500: catatui.RgbFromU32(0x4caf50),
	C600: catatui.RgbFromU32(0x43a047),
	C700: catatui.RgbFromU32(0x388e3c),
	C800: catatui.RgbFromU32(0x2e7d32),
	C900: catatui.RgbFromU32(0x1b5e20),
	A100: catatui.RgbFromU32(0xb9f6ca),
	A200: catatui.RgbFromU32(0x69f0ae),
	A400: catatui.RgbFromU32(0x00e676),
	A700: catatui.RgbFromU32(0x00c853),
}

// LightGreen is the light green ramp, with accents.
var LightGreen = AccentedPalette{
	C50:  catatui.RgbFromU32(0xf1f8e9),
	C100: catatui.RgbFromU32(0xdcedc8),
	C200: catatui.RgbFromU32(0xc5e1a5),
	C300: catatui.RgbFromU32(0xaed581),
	C400: catatui.RgbFromU32(0x9ccc65),
	C500: catatui.RgbFromU32(0x8bc34a),
	C600: catatui.RgbFromU32(0x7cb342),
	C700: catatui.RgbFromU32(0x689f38),
	C800: catatui.RgbFromU32(0x558b2f),
	C900: catatui.RgbFromU32(0x33691e),
	A100: catatui.RgbFromU32(0xccff90),
	A200: catatui.RgbFromU32(0xb2ff59),
	A400: catatui.RgbFromU32(0x76ff03),
	A700: catatui.RgbFromU32(0x64dd17),
}

// Lime is the lime ramp, with accents.
var Lime = AccentedPalette{
	C50:  catatui.RgbFromU32(0xf9fbe7),
	C100: catatui.RgbFromU32(0xf0f4c3),
	C200: catatui.RgbFromU32(0xe6ee9c),
	C300: catatui.RgbFromU32(0xdce775),
	C400: catatui.RgbFromU32(0xd4e157),
	C500: catatui.RgbFromU32(0xcddc39),
	C600: catatui.RgbFromU32(0xc0ca33),
	C700: catatui.RgbFromU32(0xafb42b),
	C800: catatui.RgbFromU32(0x9e9d24),
	C900: catatui.RgbFromU32(0x827717),
	A100: catatui.RgbFromU32(0xf4ff81),
	A200: catatui.RgbFromU32(0xeeff41),
	A400: catatui.RgbFromU32(0xc6ff00),
	A700: catatui.RgbFromU32(0xaeea00),
}

// Yellow is the yellow ramp, with accents.
var Yellow = AccentedPalette{
	C50:  catatui.RgbFromU32(0xfffde7),
	C100: catatui.RgbFromU32(0xfff9c4),
	C200: catatui.RgbFromU32(0xfff59d),
	C300: catatui.RgbFromU32(0xfff176),
	C400: catatui.RgbFromU32(0xffee58),
	C500: catatui.RgbFromU32(0xffeb3b),
	C600: catatui.RgbFromU32(0xfdd835),
	C700: catatui.RgbFromU32(0xfbc02d),
	C800: catatui.RgbFromU32(0xf9a825),
	C900: catatui.RgbFromU32(0xf57f17),
	A100: catatui.RgbFromU32(0xffff8d),
	A200: catatui.RgbFromU32(0xffff00),
	A400: catatui.RgbFromU32(0xffea00),
	A700: catatui.RgbFromU32(0xffd600),
}

// Amber is the amber ramp, with accents.
var Amber = AccentedPalette{
	C50:  catatui.RgbFromU32(0xfff8e1),
	C100: catatui.RgbFromU32(0xffecb3),
	C200: catatui.RgbFromU32(0xffe082),
	C300: catatui.RgbFromU32(0xffd54f),
	C400: catatui.RgbFromU32(0xffca28),
	C500: catatui.RgbFromU32(0xffc107),
	C600: catatui.RgbFromU32(0xffb300),
	C700: catatui.RgbFromU32(0xffa000),
	C800: catatui.RgbFromU32(0xff8f00),
	C900: catatui.RgbFromU32(0xff6f00),
	A100: catatui.RgbFromU32(0xffe57f),
	A200: catatui.RgbFromU32(0xffd740),
	A400: catatui.RgbFromU32(0xffc400),
	A700: catatui.RgbFromU32(0xffab00),
}

// Orange is the orange ramp, with accents.
var Orange = AccentedPalette{
	C50:  catatui.RgbFromU32(0xfff3e0),
	C100: catatui.RgbFromU32(0xffe0b2),
	C200: catatui.RgbFromU32(0xffcc80),
	C300: catatui.RgbFromU32(0xffb74d),
	C400: catatui.RgbFromU32(0xffa726),
	C500: catatui.RgbFromU32(0xff9800),
	C600: catatui.RgbFromU32(0xfb8c00),
	C700: catatui.RgbFromU32(0xf57c00),
	C800: catatui.RgbFromU32(0xef6c00),
	C900: catatui.RgbFromU32(0xe65100),
	A100: catatui.RgbFromU32(0xffd180),
	A200: catatui.RgbFromU32(0xffab40),
	A400: catatui.RgbFromU32(0xff9100),
	A700: catatui.RgbFromU32(0xff6d00),
}

// DeepOrange is the deep orange ramp, with accents.
var DeepOrange = AccentedPalette{
	C50:  catatui.RgbFromU32(0xfbe9e7),
	C100: catatui.RgbFromU32(0xffccbc),
	C200: catatui.RgbFromU32(0xffab91),
	C300: catatui.RgbFromU32(0xff8a65),
	C400: catatui.RgbFromU32(0xff7043),
	C500: catatui.RgbFromU32(0xff5722),
	C600: catatui.RgbFromU32(0xf4511e),
	C700: catatui.RgbFromU32(0xe64a19),
	C800: catatui.RgbFromU32(0xd84315),
	C900: catatui.RgbFromU32(0xbf360c),
	A100: catatui.RgbFromU32(0xff9e80),
	A200: catatui.RgbFromU32(0xff6e40),
	A400: catatui.RgbFromU32(0xff3d00),
	A700: catatui.RgbFromU32(0xdd2c00),
}

// Brown is the brown ramp.
var Brown = Palette{
	C50:  catatui.RgbFromU32(0xefebe9),
	C100: catatui.RgbFromU32(0xd7ccc8),
	C200: catatui.RgbFromU32(0xbcaaa4),
	C300: catatui.RgbFromU32(0xa1887f),
	C400: catatui.RgbFromU32(0x8d6e63),
	C500: catatui.RgbFromU32(0x795548),
	C600: catatui.RgbFromU32(0x6d4c41),
	C700: catatui.RgbFromU32(0x5d4037),
	C800: catatui.RgbFromU32(0x4e342e),
	C900: catatui.RgbFromU32(0x3e2723),
}

// Gray is the gray ramp.
var Gray = Palette{
	C50:  catatui.RgbFromU32(0xfafafa),
	C100: catatui.RgbFromU32(0xf5f5f5),
	C200: catatui.RgbFromU32(0xeeeeee),
	C300: catatui.RgbFromU32(0xe0e0e0),
	C400: catatui.RgbFromU32(0xbdbdbd),
	C500: catatui.RgbFromU32(0x9e9e9e),
	C600: catatui.RgbFromU32(0x757575),
	C700: catatui.RgbFromU32(0x616161),
	C800: catatui.RgbFromU32(0x424242),
	C900: catatui.RgbFromU32(0x212121),
}

// BlueGray is the blue gray ramp.
var BlueGray = Palette{
	C50:  catatui.RgbFromU32(0xeceff1),
	C100: catatui.RgbFromU32(0xcfd8dc),
	C200: catatui.RgbFromU32(0xb0bec5),
	C300: catatui.RgbFromU32(0x90a4ae),
	C400: catatui.RgbFromU32(0x78909c),
	C500: catatui.RgbFromU32(0x607d8b),
	C600: catatui.RgbFromU32(0x546e7a),
	C700: catatui.RgbFromU32(0x455a64),
	C800: catatui.RgbFromU32(0x37474f),
	C900: catatui.RgbFromU32(0x263238),
}
