// Code generated from ratatui-core/src/layout/layout.rs @ ratatui-v0.30.2 by
// scratch_gen.py. DO NOT EDIT BY HAND.
//
// These are ratatui's own layout case tables, translated mechanically. They are
// the fidelity gate for the layout port: if the Cassowary solver, the strength
// ladder or the flex handling drifts from ratatui, these fail.

package catatui

// lettersCases are driven by ratatui's `letters` helper: split a one-row area
// of the given width, fill each resulting segment with a repeated letter, and
// compare the rendered row against the expected string.
var lettersCases = []struct {
	name        string
	flex        Flex
	width       uint16
	constraints []Constraint
	expected    string
}{
	{"length", FlexLegacy, 1, []Constraint{Length(0)}, "a"},
	{"length", FlexLegacy, 1, []Constraint{Length(1)}, "a"},
	{"length", FlexLegacy, 1, []Constraint{Length(2)}, "a"},
	{"length", FlexLegacy, 2, []Constraint{Length(0)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(1)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(2)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(3)}, "aa"},
	{"length", FlexLegacy, 1, []Constraint{Length(0), Length(0)}, "b"},
	{"length", FlexLegacy, 1, []Constraint{Length(0), Length(1)}, "b"},
	{"length", FlexLegacy, 1, []Constraint{Length(0), Length(2)}, "b"},
	{"length", FlexLegacy, 1, []Constraint{Length(1), Length(0)}, "a"},
	{"length", FlexLegacy, 1, []Constraint{Length(1), Length(1)}, "a"},
	{"length", FlexLegacy, 1, []Constraint{Length(1), Length(2)}, "a"},
	{"length", FlexLegacy, 1, []Constraint{Length(2), Length(0)}, "a"},
	{"length", FlexLegacy, 1, []Constraint{Length(2), Length(1)}, "a"},
	{"length", FlexLegacy, 1, []Constraint{Length(2), Length(2)}, "a"},
	{"length", FlexLegacy, 2, []Constraint{Length(0), Length(0)}, "bb"},
	{"length", FlexLegacy, 2, []Constraint{Length(0), Length(1)}, "bb"},
	{"length", FlexLegacy, 2, []Constraint{Length(0), Length(2)}, "bb"},
	{"length", FlexLegacy, 2, []Constraint{Length(0), Length(3)}, "bb"},
	{"length", FlexLegacy, 2, []Constraint{Length(1), Length(0)}, "ab"},
	{"length", FlexLegacy, 2, []Constraint{Length(1), Length(1)}, "ab"},
	{"length", FlexLegacy, 2, []Constraint{Length(1), Length(2)}, "ab"},
	{"length", FlexLegacy, 2, []Constraint{Length(1), Length(3)}, "ab"},
	{"length", FlexLegacy, 2, []Constraint{Length(2), Length(0)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(2), Length(1)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(2), Length(2)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(2), Length(3)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(3), Length(0)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(3), Length(1)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(3), Length(2)}, "aa"},
	{"length", FlexLegacy, 2, []Constraint{Length(3), Length(3)}, "aa"},
	{"length", FlexLegacy, 3, []Constraint{Length(2), Length(2)}, "aab"},
	{"max", FlexLegacy, 1, []Constraint{Max(0)}, "a"},
	{"max", FlexLegacy, 1, []Constraint{Max(1)}, "a"},
	{"max", FlexLegacy, 1, []Constraint{Max(2)}, "a"},
	{"max", FlexLegacy, 2, []Constraint{Max(0)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(1)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(2)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(3)}, "aa"},
	{"max", FlexLegacy, 1, []Constraint{Max(0), Max(0)}, "b"},
	{"max", FlexLegacy, 1, []Constraint{Max(0), Max(1)}, "b"},
	{"max", FlexLegacy, 1, []Constraint{Max(0), Max(2)}, "b"},
	{"max", FlexLegacy, 1, []Constraint{Max(1), Max(0)}, "a"},
	{"max", FlexLegacy, 1, []Constraint{Max(1), Max(1)}, "a"},
	{"max", FlexLegacy, 1, []Constraint{Max(1), Max(2)}, "a"},
	{"max", FlexLegacy, 1, []Constraint{Max(2), Max(0)}, "a"},
	{"max", FlexLegacy, 1, []Constraint{Max(2), Max(1)}, "a"},
	{"max", FlexLegacy, 1, []Constraint{Max(2), Max(2)}, "a"},
	{"max", FlexLegacy, 2, []Constraint{Max(0), Max(0)}, "bb"},
	{"max", FlexLegacy, 2, []Constraint{Max(0), Max(1)}, "bb"},
	{"max", FlexLegacy, 2, []Constraint{Max(0), Max(2)}, "bb"},
	{"max", FlexLegacy, 2, []Constraint{Max(0), Max(3)}, "bb"},
	{"max", FlexLegacy, 2, []Constraint{Max(1), Max(0)}, "ab"},
	{"max", FlexLegacy, 2, []Constraint{Max(1), Max(1)}, "ab"},
	{"max", FlexLegacy, 2, []Constraint{Max(1), Max(2)}, "ab"},
	{"max", FlexLegacy, 2, []Constraint{Max(1), Max(3)}, "ab"},
	{"max", FlexLegacy, 2, []Constraint{Max(2), Max(0)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(2), Max(1)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(2), Max(2)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(2), Max(3)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(3), Max(0)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(3), Max(1)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(3), Max(2)}, "aa"},
	{"max", FlexLegacy, 2, []Constraint{Max(3), Max(3)}, "aa"},
	{"max", FlexLegacy, 3, []Constraint{Max(2), Max(2)}, "aab"},
	{"min", FlexLegacy, 1, []Constraint{Min(0), Min(0)}, "b"},
	{"min", FlexLegacy, 1, []Constraint{Min(0), Min(1)}, "b"},
	{"min", FlexLegacy, 1, []Constraint{Min(0), Min(2)}, "b"},
	{"min", FlexLegacy, 1, []Constraint{Min(1), Min(0)}, "a"},
	{"min", FlexLegacy, 1, []Constraint{Min(1), Min(1)}, "a"},
	{"min", FlexLegacy, 1, []Constraint{Min(1), Min(2)}, "a"},
	{"min", FlexLegacy, 1, []Constraint{Min(2), Min(0)}, "a"},
	{"min", FlexLegacy, 1, []Constraint{Min(2), Min(1)}, "a"},
	{"min", FlexLegacy, 1, []Constraint{Min(2), Min(2)}, "a"},
	{"min", FlexLegacy, 2, []Constraint{Min(0), Min(0)}, "bb"},
	{"min", FlexLegacy, 2, []Constraint{Min(0), Min(1)}, "bb"},
	{"min", FlexLegacy, 2, []Constraint{Min(0), Min(2)}, "bb"},
	{"min", FlexLegacy, 2, []Constraint{Min(0), Min(3)}, "bb"},
	{"min", FlexLegacy, 2, []Constraint{Min(1), Min(0)}, "ab"},
	{"min", FlexLegacy, 2, []Constraint{Min(1), Min(1)}, "ab"},
	{"min", FlexLegacy, 2, []Constraint{Min(1), Min(2)}, "ab"},
	{"min", FlexLegacy, 2, []Constraint{Min(1), Min(3)}, "ab"},
	{"min", FlexLegacy, 2, []Constraint{Min(2), Min(0)}, "aa"},
	{"min", FlexLegacy, 2, []Constraint{Min(2), Min(1)}, "aa"},
	{"min", FlexLegacy, 2, []Constraint{Min(2), Min(2)}, "aa"},
	{"min", FlexLegacy, 2, []Constraint{Min(2), Min(3)}, "aa"},
	{"min", FlexLegacy, 2, []Constraint{Min(3), Min(0)}, "aa"},
	{"min", FlexLegacy, 2, []Constraint{Min(3), Min(1)}, "aa"},
	{"min", FlexLegacy, 2, []Constraint{Min(3), Min(2)}, "aa"},
	{"min", FlexLegacy, 2, []Constraint{Min(3), Min(3)}, "aa"},
	{"min", FlexLegacy, 3, []Constraint{Min(2), Min(2)}, "aab"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(0)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(25)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(50)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(90)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(100)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(200)}, "a"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(0)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(10)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(25)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(50)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(66)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(100)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(200)}, "aa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(0)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(10)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(25)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(50)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(66)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(100)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(200)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(0), Percentage(0)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(0), Percentage(10)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(0), Percentage(50)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(0), Percentage(90)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(0), Percentage(100)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(0), Percentage(200)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(10), Percentage(0)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(10), Percentage(10)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(10), Percentage(50)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(10), Percentage(90)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(10), Percentage(100)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(10), Percentage(200)}, "b"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(50), Percentage(0)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(50), Percentage(50)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(50), Percentage(100)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(50), Percentage(200)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(90), Percentage(0)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(90), Percentage(50)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(90), Percentage(100)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(90), Percentage(200)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(100), Percentage(0)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(100), Percentage(50)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(100), Percentage(100)}, "a"},
	{"percentage", FlexLegacy, 1, []Constraint{Percentage(100), Percentage(200)}, "a"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(0), Percentage(0)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(0), Percentage(25)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(0), Percentage(50)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(0), Percentage(100)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(0), Percentage(200)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(10), Percentage(0)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(10), Percentage(25)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(10), Percentage(50)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(10), Percentage(100)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(10), Percentage(200)}, "bb"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(25), Percentage(0)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(25), Percentage(25)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(25), Percentage(50)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(25), Percentage(100)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(25), Percentage(200)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(33), Percentage(0)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(33), Percentage(25)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(33), Percentage(50)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(33), Percentage(100)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(33), Percentage(200)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(50), Percentage(0)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(50), Percentage(50)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(50), Percentage(100)}, "ab"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(100), Percentage(0)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(100), Percentage(50)}, "aa"},
	{"percentage", FlexLegacy, 2, []Constraint{Percentage(100), Percentage(100)}, "aa"},
	{"percentage", FlexLegacy, 3, []Constraint{Percentage(33), Percentage(33)}, "abb"},
	{"percentage", FlexLegacy, 3, []Constraint{Percentage(33), Percentage(66)}, "abb"},
	{"percentage", FlexLegacy, 4, []Constraint{Percentage(33), Percentage(33)}, "abbb"},
	{"percentage", FlexLegacy, 4, []Constraint{Percentage(33), Percentage(66)}, "abbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(0), Percentage(0)}, "bbbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(0), Percentage(25)}, "bbbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(0), Percentage(50)}, "bbbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(0), Percentage(100)}, "bbbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(0), Percentage(200)}, "bbbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(10), Percentage(0)}, "abbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(10), Percentage(25)}, "abbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(10), Percentage(50)}, "abbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(10), Percentage(100)}, "abbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(10), Percentage(200)}, "abbbbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(25), Percentage(0)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(25), Percentage(25)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(25), Percentage(50)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(25), Percentage(100)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(25), Percentage(200)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(33), Percentage(0)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(33), Percentage(25)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(33), Percentage(50)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(33), Percentage(100)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(33), Percentage(200)}, "aaabbbbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(50), Percentage(0)}, "aaaaabbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(50), Percentage(50)}, "aaaaabbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(50), Percentage(100)}, "aaaaabbbbb"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(100), Percentage(0)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(100), Percentage(50)}, "aaaaaaaaaa"},
	{"percentage", FlexLegacy, 10, []Constraint{Percentage(100), Percentage(100)}, "aaaaaaaaaa"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(0), Percentage(0)}, "          "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(0), Percentage(25)}, "bbb       "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(0), Percentage(50)}, "bbbbb     "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(0), Percentage(100)}, "bbbbbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(0), Percentage(200)}, "bbbbbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(10), Percentage(0)}, "a         "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(10), Percentage(25)}, "abbb      "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(10), Percentage(50)}, "abbbbb    "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(10), Percentage(100)}, "abbbbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(10), Percentage(200)}, "abbbbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(25), Percentage(0)}, "aaa       "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(25), Percentage(25)}, "aaabb     "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(25), Percentage(50)}, "aaabbbbb  "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(25), Percentage(100)}, "aaabbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(25), Percentage(200)}, "aaabbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(33), Percentage(0)}, "aaa       "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(33), Percentage(25)}, "aaabbb    "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(33), Percentage(50)}, "aaabbbbb  "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(33), Percentage(100)}, "aaabbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(33), Percentage(200)}, "aaabbbbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(50), Percentage(0)}, "aaaaa     "},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(50), Percentage(50)}, "aaaaabbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(50), Percentage(100)}, "aaaaabbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(100), Percentage(0)}, "aaaaaaaaaa"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(100), Percentage(50)}, "aaaaabbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(100), Percentage(100)}, "aaaaabbbbb"},
	{"percentage_start", FlexStart, 10, []Constraint{Percentage(100), Percentage(200)}, "aaaaabbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(0)}, "          "},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(25)}, "        bb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(50)}, "     bbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(100)}, "bbbbbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(0), Percentage(200)}, "bbbbbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(0)}, "a         "},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(25)}, "a       bb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(50)}, "a    bbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(100)}, "abbbbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(10), Percentage(200)}, "abbbbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(0)}, "aaa       "},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(25)}, "aaa     bb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(50)}, "aaa  bbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(100)}, "aaabbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(25), Percentage(200)}, "aaabbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(0)}, "aaa       "},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(25)}, "aaa     bb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(50)}, "aaa  bbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(100)}, "aaabbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(33), Percentage(200)}, "aaabbbbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(50), Percentage(0)}, "aaaaa     "},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(50), Percentage(50)}, "aaaaabbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(50), Percentage(100)}, "aaaaabbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(0)}, "aaaaaaaaaa"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(50)}, "aaaaabbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(100)}, "aaaaabbbbb"},
	{"percentage_spacebetween", FlexSpaceBetween, 10, []Constraint{Percentage(100), Percentage(200)}, "aaaaabbbbb"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(0, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 4)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 2)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(9, 10)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(2, 1)}, "a"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(0, 1)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 10)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 4)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 2)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(2, 3)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 1)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(2, 1)}, "aa"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(1, 10)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(9, 10)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(1, 10)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(9, 10)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "b"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 2), Ratio(2, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(0, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(1, 2)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(1, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(9, 10), Ratio(2, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "a"},
	{"ratio", FlexLegacy, 1, []Constraint{Ratio(1, 1), Ratio(2, 1)}, "a"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "bb"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "ab"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aa"},
	{"ratio", FlexLegacy, 2, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aa"},
	{"ratio", FlexLegacy, 3, []Constraint{Ratio(1, 3), Ratio(1, 3)}, "abb"},
	{"ratio", FlexLegacy, 3, []Constraint{Ratio(1, 3), Ratio(2,3)}, "abb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "bbbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "bbbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "bbbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bbbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bbbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "abbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "abbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "abbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "abbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "abbbbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "aaabbbbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "aaaaabbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "aaaaabbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "aaaaabbbbb"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aaaaaaaaaa"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aaaaaaaaaa"},
	{"ratio", FlexLegacy, 10, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aaaaaaaaaa"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "          "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "bbb       "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "bbbbb     "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bbbbbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bbbbbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "a         "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "abbb      "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "abbbbb    "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "abbbbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "abbbbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "aaa       "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "aaabb     "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "aaabbbbb  "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "aaabbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "aaabbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "aaa       "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "aaabbb    "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "aaabbbbb  "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "aaabbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "aaabbbbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "aaaaa     "},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "aaaaabbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "aaaaabbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aaaaaaaaaa"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aaaaabbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aaaaabbbbb"},
	{"ratio_start", FlexStart, 10, []Constraint{Ratio(1, 1), Ratio(2, 1)}, "aaaaabbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(0, 1)}, "          "},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(1, 4)}, "        bb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(1, 2)}, "     bbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(1, 1)}, "bbbbbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(0, 1), Ratio(2, 1)}, "bbbbbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(0, 1)}, "a         "},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(1, 4)}, "a       bb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(1, 2)}, "a    bbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(1, 1)}, "abbbbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 10), Ratio(2, 1)}, "abbbbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(0, 1)}, "aaa       "},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(1, 4)}, "aaa     bb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(1, 2)}, "aaa  bbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(1, 1)}, "aaabbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 4), Ratio(2, 1)}, "aaabbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(0, 1)}, "aaa       "},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(1, 4)}, "aaa     bb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(1, 2)}, "aaa  bbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(1, 1)}, "aaabbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 3), Ratio(2, 1)}, "aaabbbbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 2), Ratio(0, 1)}, "aaaaa     "},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 2), Ratio(1, 2)}, "aaaaabbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 2), Ratio(1, 1)}, "aaaaabbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(0, 1)}, "aaaaaaaaaa"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(1, 2)}, "aaaaabbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(1, 1)}, "aaaaabbbbb"},
	{"ratio_spacebetween", FlexSpaceBetween, 10, []Constraint{Ratio(1, 1), Ratio(2, 1)}, "aaaaabbbbb"},
}

// rangeCases check the left..right span of each segment.
var rangeCases = []struct {
	name        string
	width       uint16
	flex        Flex
	constraints []Constraint
	expected    []rng
}{
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Min(100)}, []rng{{0, 0}, {0, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Min(0)}, []rng{{0, 25}, {25, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Max(0)}, []rng{{0, 100}, {100, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Max(100)}, []rng{{0, 25}, {25, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Percentage(25)}, []rng{{0, 25}, {25, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Percentage(25), Length(25)}, []rng{{0, 75}, {75, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Ratio(1, 4)}, []rng{{0, 25}, {25, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Ratio(1, 4), Length(25)}, []rng{{0, 75}, {75, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Length(25)}, []rng{{0, 25}, {25, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Length(25), Length(25)}, []rng{{0, 25}, {25, 50}, {50, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(15), Length(35), Length(25)}, []rng{{0, 15}, {15, 50}, {50, 100}}},
	{"constraint_length", 100, FlexLegacy, []Constraint{Length(25), Length(25), Length(25)}, []rng{{0, 25}, {25, 50}, {50, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Min(25), Length(25), Max(25)}, []rng{{0, 50}, {50, 75}, {75, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Max(25), Length(25), Min(25)}, []rng{{0, 25}, {25, 50}, {50, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Length(33), Length(33), Length(33)}, []rng{{0, 33}, {33, 66}, {66, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Length(25), Length(25), Length(25)}, []rng{{0, 25}, {25, 50}, {50, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Percentage(25), Length(25), Ratio(1, 4)}, []rng{{0, 25}, {25, 50}, {50, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Length(25), Ratio(1, 4), Percentage(25)}, []rng{{0, 25}, {25, 75}, {75, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Ratio(1, 4), Length(25), Percentage(25)}, []rng{{0, 50}, {50, 75}, {75, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Ratio(1, 4), Percentage(25), Length(25)}, []rng{{0, 50}, {50, 75}, {75, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Length(100), Length(1), Min(20)}, []rng{{0, 80}, {80, 80}, {80, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Min(20), Length(1), Length(100)}, []rng{{0, 20}, {20, 21}, {21, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Fill(1), Length(10), Fill(1)}, []rng{{0, 45}, {45, 55}, {55, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Fill(1), Length(10), Fill(2)}, []rng{{0, 30}, {30, 40}, {40, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Fill(1), Length(10), Fill(4)}, []rng{{0, 18}, {18, 28}, {28, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Fill(1), Length(10), Fill(5)}, []rng{{0, 15}, {15, 25}, {25, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Length(25), Length(25), Length(25)}, []rng{{0, 25}, {25, 50}, {50, 100}}},
	{"length_is_higher_priority", 100, FlexLegacy, []Constraint{Length(25), Length(25), Length(25)}, []rng{{0, 25}, {25, 50}, {50, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(2), Fill(1), Fill(1)}, []rng{{0, 20}, {20, 60}, {60, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(2), Fill(3), Fill(4)}, []rng{{0, 10}, {10, 30}, {30, 60}, {60, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(4), Fill(3), Fill(2), Fill(1)}, []rng{{0, 40}, {40, 70}, {70, 90}, {90, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(3), Fill(2), Fill(4)}, []rng{{0, 10}, {10, 40}, {40, 60}, {60, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(3), Length(50), Fill(2), Fill(4)}, []rng{{0, 5}, {5, 20}, {20, 70}, {70, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(3), Percentage(50), Fill(2), Fill(4)}, []rng{{0, 5}, {5, 20}, {20, 70}, {70, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(3), Min(50), Fill(2), Fill(4)}, []rng{{0, 5}, {5, 20}, {20, 70}, {70, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(3), Max(50), Fill(2), Fill(4)}, []rng{{0, 5}, {5, 20}, {20, 70}, {70, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Fill(1), Fill(0)}, []rng{{0, 0}, {0, 100}, {100, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Length(1), Fill(0)}, []rng{{0, 50}, {50, 51}, {51, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Percentage(1), Fill(0)}, []rng{{0, 50}, {50, 51}, {51, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Min(1), Fill(0)}, []rng{{0, 50}, {50, 51}, {51, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Max(1), Fill(0)}, []rng{{0, 50}, {50, 51}, {51, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Fill(2), Fill(0), Fill(1)}, []rng{{0, 0}, {0, 67}, {67, 67}, {67, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Fill(2), Percentage(20)}, []rng{{0, 0}, {0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Fill(0), Percentage(20)}, []rng{{0, 40}, {40, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Ratio(1, 5)}, []rng{{0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Fill(65535)}, []rng{{0, 0}, {0, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(65535), Fill(0)}, []rng{{0, 100}, {100, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Percentage(20)}, []rng{{0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Percentage(20)}, []rng{{0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(65535), Percentage(20)}, []rng{{0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(65535), Fill(0), Percentage(20)}, []rng{{0, 80}, {80, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Length(20)}, []rng{{0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Min(20)}, []rng{{0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(0), Max(20)}, []rng{{0, 80}, {80, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(1), Fill(1), Min(30), Length(50)}, []rng{{0, 7}, {7, 13}, {13, 20}, {20, 50}, {50, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(1), Fill(1), Length(50), Length(50)}, []rng{{0, 0}, {0, 0}, {0, 0}, {0, 50}, {50, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(1), Fill(1), Length(75), Length(50)}, []rng{{0, 0}, {0, 0}, {0, 0}, {0, 75}, {75, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(1), Fill(1), Min(50), Max(50)}, []rng{{0, 0}, {0, 0}, {0, 0}, {0, 50}, {50, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(1), Fill(1), Ratio(1, 1)}, []rng{{0, 0}, {0, 0}, {0, 0}, {0, 100}}},
	{"fill", 100, FlexLegacy, []Constraint{Fill(1), Fill(1), Fill(1), Percentage(100)}, []rng{{0, 0}, {0, 0}, {0, 0}, {0, 100}}},
	{"percentage_parameterized", 100, FlexLegacy, []Constraint{Min(0), Percentage(20)}, []rng{{0, 80}, {80, 100}}},
	{"percentage_parameterized", 100, FlexLegacy, []Constraint{Max(0), Percentage(20)}, []rng{{0, 0}, {0, 100}}},
	{"min_max", 100, FlexLegacy, []Constraint{Max(100), Min(0)}, []rng{{0, 100}, {100, 100}}},
	{"min_max", 100, FlexLegacy, []Constraint{Min(0), Max(100)}, []rng{{0, 0}, {0, 100}}},
	{"min_max", 100, FlexLegacy, []Constraint{Length(65535), Min(10)}, []rng{{0, 90}, {90, 100}}},
	{"min_max", 100, FlexLegacy, []Constraint{Min(10), Length(65535)}, []rng{{0, 10}, {10, 100}}},
	{"min_max", 100, FlexLegacy, []Constraint{Length(0), Max(10)}, []rng{{0, 90}, {90, 100}}},
	{"min_max", 100, FlexLegacy, []Constraint{Max(10), Length(0)}, []rng{{0, 10}, {10, 100}}},
	{"fixed_with_50_width", 50, FlexLegacy, []Constraint{Fill(1), Length(10), Fill(2)}, []rng{{0, 13}, {13, 23}, {23, 50}}},
	{"fixed_with_50_width", 50, FlexLegacy, []Constraint{Length(10), Fill(2), Fill(1)}, []rng{{0, 10}, {10, 37}, {37, 50}}},
}

// flexRangeCases check the span of each segment under an explicit flex mode,
// in a 100-column area.
var flexRangeCases = []struct {
	name        string
	constraints []Constraint
	flex        Flex
	expected    []rng
}{
	{"flex_constraint", []Constraint{Length(50)}, FlexLegacy, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexStart, []rng{{0, 50}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexEnd, []rng{{50, 100}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexCenter, []rng{{25, 75}}},
	{"flex_constraint", []Constraint{Ratio(1, 2)}, FlexLegacy, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Ratio(1, 2)}, FlexStart, []rng{{0, 50}}},
	{"flex_constraint", []Constraint{Ratio(1, 2)}, FlexEnd, []rng{{50, 100}}},
	{"flex_constraint", []Constraint{Ratio(1, 2)}, FlexCenter, []rng{{25, 75}}},
	{"flex_constraint", []Constraint{Percentage(50)}, FlexLegacy, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Percentage(50)}, FlexStart, []rng{{0, 50}}},
	{"flex_constraint", []Constraint{Percentage(50)}, FlexEnd, []rng{{50, 100}}},
	{"flex_constraint", []Constraint{Percentage(50)}, FlexCenter, []rng{{25, 75}}},
	{"flex_constraint", []Constraint{Min(50)}, FlexLegacy, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Min(50)}, FlexStart, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Min(50)}, FlexEnd, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Min(50)}, FlexCenter, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Max(50)}, FlexLegacy, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Max(50)}, FlexStart, []rng{{0, 50}}},
	{"flex_constraint", []Constraint{Max(50)}, FlexEnd, []rng{{50, 100}}},
	{"flex_constraint", []Constraint{Max(50)}, FlexCenter, []rng{{25, 75}}},
	{"flex_constraint", []Constraint{Min(1)}, FlexSpaceBetween, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Max(20)}, FlexSpaceBetween, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Length(20)}, FlexSpaceBetween, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Length(25), Length(25)}, FlexLegacy, []rng{{0, 25}, {25, 100}}},
	{"flex_constraint", []Constraint{Length(25), Length(25)}, FlexStart, []rng{{0, 25}, {25, 50}}},
	{"flex_constraint", []Constraint{Length(25), Length(25)}, FlexCenter, []rng{{25, 50}, {50, 75}}},
	{"flex_constraint", []Constraint{Length(25), Length(25)}, FlexEnd, []rng{{50, 75}, {75, 100}}},
	{"flex_constraint", []Constraint{Length(25), Length(25)}, FlexSpaceBetween, []rng{{0, 25}, {75, 100}}},
	{"flex_constraint", []Constraint{Length(25), Length(25)}, FlexSpaceEvenly, []rng{{17, 42}, {58, 83}}},
	{"flex_constraint", []Constraint{Length(25), Length(25)}, FlexSpaceAround, []rng{{13, 38}, {63, 88}}},
	{"flex_constraint", []Constraint{Percentage(25), Percentage(25)}, FlexLegacy, []rng{{0, 25}, {25, 100}}},
	{"flex_constraint", []Constraint{Percentage(25), Percentage(25)}, FlexStart, []rng{{0, 25}, {25, 50}}},
	{"flex_constraint", []Constraint{Percentage(25), Percentage(25)}, FlexCenter, []rng{{25, 50}, {50, 75}}},
	{"flex_constraint", []Constraint{Percentage(25), Percentage(25)}, FlexEnd, []rng{{50, 75}, {75, 100}}},
	{"flex_constraint", []Constraint{Percentage(25), Percentage(25)}, FlexSpaceBetween, []rng{{0, 25}, {75, 100}}},
	{"flex_constraint", []Constraint{Percentage(25), Percentage(25)}, FlexSpaceEvenly, []rng{{17, 42}, {58, 83}}},
	{"flex_constraint", []Constraint{Percentage(25), Percentage(25)}, FlexSpaceAround, []rng{{13, 38}, {63, 88}}},
	{"flex_constraint", []Constraint{Min(25), Min(25)}, FlexLegacy, []rng{{0, 25}, {25, 100}}},
	{"flex_constraint", []Constraint{Min(25), Min(25)}, FlexStart, []rng{{0, 50}, {50, 100}}},
	{"flex_constraint", []Constraint{Min(25), Min(25)}, FlexCenter, []rng{{0, 50}, {50, 100}}},
	{"flex_constraint", []Constraint{Min(25), Min(25)}, FlexEnd, []rng{{0, 50}, {50, 100}}},
	{"flex_constraint", []Constraint{Min(25), Min(25)}, FlexSpaceBetween, []rng{{0, 50}, {50, 100}}},
	{"flex_constraint", []Constraint{Min(25), Min(25)}, FlexSpaceEvenly, []rng{{0, 50}, {50, 100}}},
	{"flex_constraint", []Constraint{Min(25), Min(25)}, FlexSpaceAround, []rng{{0, 50}, {50, 100}}},
	{"flex_constraint", []Constraint{Max(25), Max(25)}, FlexLegacy, []rng{{0, 25}, {25, 100}}},
	{"flex_constraint", []Constraint{Max(25), Max(25)}, FlexStart, []rng{{0, 25}, {25, 50}}},
	{"flex_constraint", []Constraint{Max(25), Max(25)}, FlexCenter, []rng{{25, 50}, {50, 75}}},
	{"flex_constraint", []Constraint{Max(25), Max(25)}, FlexEnd, []rng{{50, 75}, {75, 100}}},
	{"flex_constraint", []Constraint{Max(25), Max(25)}, FlexSpaceBetween, []rng{{0, 25}, {75, 100}}},
	{"flex_constraint", []Constraint{Max(25), Max(25)}, FlexSpaceEvenly, []rng{{17, 42}, {58, 83}}},
	{"flex_constraint", []Constraint{Max(25), Max(25)}, FlexSpaceAround, []rng{{13, 38}, {63, 88}}},
	{"flex_constraint", []Constraint{Length(25), Length(25), Length(25)}, FlexSpaceBetween, []rng{{0, 25}, {38, 63}, {75, 100}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexLegacy, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexStart, []rng{{0, 50}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexEnd, []rng{{50, 100}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexCenter, []rng{{25, 75}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexSpaceBetween, []rng{{0, 100}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexSpaceEvenly, []rng{{25, 75}}},
	{"flex_constraint", []Constraint{Length(50)}, FlexSpaceAround, []rng{{25, 75}}},
}

// pairCases check the (x, width) of each segment.
var pairCases = []struct {
	name        string
	constraints []Constraint
	flex        Flex
	spacing     int
	expected    []pair
}{
	{"fill_vs_flex", []Constraint{Length(10), Fill(1), Length(10)}, FlexLegacy, 0, []pair{{0, 10}, {10, 80}, {90, 10}}},
	{"fill_vs_flex", []Constraint{Length(10), Length(10)}, FlexSpaceBetween, 0, []pair{{0, 10}, {90, 10}}},
	{"fill_vs_flex", []Constraint{Fill(1), Length(10), Fill(1), Length(10), Fill(1)}, FlexLegacy, 0, []pair{{0, 27}, {27, 10}, {37, 26}, {63, 10}, {73, 27}}},
	{"fill_vs_flex", []Constraint{Length(10), Length(10)}, FlexSpaceEvenly, 0, []pair{{27, 10}, {63, 10}}},
	{"fill_vs_flex", []Constraint{Length(10), Length(10), Fill(1)}, FlexLegacy, 0, []pair{{0, 10}, {10, 10}, {20, 80}}},
	{"fill_vs_flex", []Constraint{Length(10), Length(10)}, FlexStart, 0, []pair{{0, 10}, {10, 10}}},
	{"fill_vs_flex", []Constraint{Fill(1), Length(10), Length(10)}, FlexLegacy, 0, []pair{{0, 80}, {80, 10}, {90, 10}}},
	{"fill_vs_flex", []Constraint{Length(10), Length(10)}, FlexEnd, 0, []pair{{80, 10}, {90, 10}}},
	{"fill_vs_flex", []Constraint{Fill(1), Length(10), Length(10), Fill(1)}, FlexLegacy, 0, []pair{{0, 40}, {40, 10}, {50, 10}, {60, 40}}},
	{"fill_vs_flex", []Constraint{Length(10), Length(10)}, FlexCenter, 0, []pair{{40, 10}, {50, 10}}},
	{"fill_vs_flex", []Constraint{Length(10), Length(10)}, FlexSpaceAround, 0, []pair{{20, 10}, {70, 10}}},
	{"legacy_vs_default", []Constraint{Min(10), Length(10)}, FlexLegacy, 0, []pair{{0, 90}, {90, 10}}},
	{"legacy_vs_default", []Constraint{Min(10), Length(10)}, FlexStart, 0, []pair{{0, 90}, {90, 10}}},
	{"legacy_vs_default", []Constraint{Min(10), Percentage(100)}, FlexLegacy, 0, []pair{{0, 10}, {10, 90}}},
	{"legacy_vs_default", []Constraint{Min(10), Percentage(100)}, FlexStart, 0, []pair{{0, 10}, {10, 90}}},
	{"legacy_vs_default", []Constraint{Percentage(50), Percentage(50)}, FlexLegacy, 0, []pair{{0, 50}, {50, 50}}},
	{"legacy_vs_default", []Constraint{Percentage(50), Percentage(50)}, FlexStart, 0, []pair{{0, 50}, {50, 50}}},
	{"constraint_specification_tests_for_priority", []Constraint{Length(25), Length(25)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Length(25), Percentage(25)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Percentage(25), Length(25)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"constraint_specification_tests_for_priority", []Constraint{Min(25), Percentage(25)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"constraint_specification_tests_for_priority", []Constraint{Percentage(25), Min(25)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Min(25), Percentage(100)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Percentage(100), Min(25)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"constraint_specification_tests_for_priority", []Constraint{Max(75), Percentage(75)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Percentage(75), Max(75)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"constraint_specification_tests_for_priority", []Constraint{Max(25), Percentage(25)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Percentage(25), Max(25)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"constraint_specification_tests_for_priority", []Constraint{Length(25), Ratio(1, 4)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Ratio(1, 4), Length(25)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"constraint_specification_tests_for_priority", []Constraint{Percentage(25), Ratio(1, 4)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Ratio(1, 4), Percentage(25)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"constraint_specification_tests_for_priority", []Constraint{Ratio(1, 4), Fill(25)}, FlexLegacy, 0, []pair{{0, 25}, {25, 75}}},
	{"constraint_specification_tests_for_priority", []Constraint{Fill(25), Ratio(1, 4)}, FlexLegacy, 0, []pair{{0, 75}, {75, 25}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexStart, 0, []pair{{0, 20}, {20, 20}, {40, 20}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexStart, -1, []pair{{0, 20}, {19, 20}, {38, 20}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexCenter, -1, []pair{{21, 20}, {40, 20}, {59, 20}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexEnd, -1, []pair{{42, 20}, {61, 20}, {80, 20}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexLegacy, -1, []pair{{0, 20}, {19, 20}, {38, 62}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceBetween, -1, []pair{{0, 20}, {40, 20}, {80, 20}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceEvenly, -1, []pair{{10, 20}, {40, 20}, {70, 20}}},
	{"flex_overlap", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceAround, -1, []pair{{7, 20}, {40, 20}, {73, 20}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexStart, 0, []pair{{0, 20}, {20, 20}, {40, 20}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexStart, 2, []pair{{0, 20}, {22, 20}, {44, 20}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexCenter, 2, []pair{{18, 20}, {40, 20}, {62, 20}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexEnd, 2, []pair{{36, 20}, {58, 20}, {80, 20}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexLegacy, 2, []pair{{0, 20}, {22, 20}, {44, 56}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceBetween, 2, []pair{{0, 20}, {40, 20}, {80, 20}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceEvenly, 2, []pair{{10, 20}, {40, 20}, {70, 20}}},
	{"flex_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceAround, 2, []pair{{7, 20}, {40, 20}, {73, 20}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexLegacy, 0, []pair{{0, 50}, {50, 50}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexSpaceEvenly, 0, []pair{{0, 50}, {50, 50}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexSpaceBetween, 0, []pair{{0, 50}, {50, 50}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexSpaceAround, 0, []pair{{0, 50}, {50, 50}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexStart, 0, []pair{{0, 50}, {50, 50}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexCenter, 0, []pair{{0, 50}, {50, 50}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexEnd, 0, []pair{{0, 50}, {50, 50}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexLegacy, 10, []pair{{0, 45}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexStart, 10, []pair{{0, 45}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexCenter, 10, []pair{{0, 45}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexEnd, 10, []pair{{0, 45}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexSpaceEvenly, 10, []pair{{10, 35}, {55, 35}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexSpaceBetween, 10, []pair{{0, 45}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Fill(1)}, FlexSpaceAround, 10, []pair{{10, 30}, {60, 30}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexLegacy, 0, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceEvenly, 0, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceBetween, 0, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceAround, 0, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexStart, 0, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexCenter, 0, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexEnd, 0, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexLegacy, 10, []pair{{0, 35}, {45, 10}, {65, 35}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexStart, 10, []pair{{0, 35}, {45, 10}, {65, 35}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexCenter, 10, []pair{{0, 35}, {45, 10}, {65, 35}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexEnd, 10, []pair{{0, 35}, {45, 10}, {65, 35}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceEvenly, 10, []pair{{10, 25}, {45, 10}, {65, 25}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceBetween, 10, []pair{{0, 35}, {45, 10}, {65, 35}}},
	{"fill_spacing", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceAround, 10, []pair{{10, 15}, {45, 10}, {75, 15}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexLegacy, -10, []pair{{0, 55}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexSpaceAround, -10, []pair{{0, 50}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexSpaceBetween, -10, []pair{{0, 55}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexStart, -10, []pair{{0, 55}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexCenter, -10, []pair{{0, 55}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexEnd, -10, []pair{{0, 55}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexSpaceEvenly, -10, []pair{{0, 50}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexLegacy, -1, []pair{{0, 51}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexStart, -1, []pair{{0, 51}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexCenter, -1, []pair{{0, 51}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexEnd, -1, []pair{{0, 51}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexSpaceAround, -1, []pair{{0, 50}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexSpaceBetween, -1, []pair{{0, 51}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Fill(1)}, FlexSpaceEvenly, -1, []pair{{0, 50}, {50, 50}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexLegacy, -10, []pair{{0, 55}, {45, 10}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceAround, -10, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceBetween, -10, []pair{{0, 55}, {45, 10}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexStart, -10, []pair{{0, 55}, {45, 10}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexCenter, -10, []pair{{0, 55}, {45, 10}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexEnd, -10, []pair{{0, 55}, {45, 10}, {45, 55}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceEvenly, -10, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexLegacy, -1, []pair{{0, 46}, {45, 10}, {54, 46}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexStart, -1, []pair{{0, 46}, {45, 10}, {54, 46}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexCenter, -1, []pair{{0, 46}, {45, 10}, {54, 46}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexEnd, -1, []pair{{0, 46}, {45, 10}, {54, 46}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceAround, -1, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceBetween, -1, []pair{{0, 46}, {45, 10}, {54, 46}}},
	{"fill_overlap", []Constraint{Fill(1), Length(10), Fill(1)}, FlexSpaceEvenly, -1, []pair{{0, 45}, {45, 10}, {55, 45}}},
	{"constraint_specification_tests_for_priority_with_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexStart, 0, []pair{{0, 20}, {20, 20}, {40, 20}}},
	{"constraint_specification_tests_for_priority_with_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexCenter, 2, []pair{{18, 20}, {40, 20}, {62, 20}}},
	{"constraint_specification_tests_for_priority_with_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexEnd, 2, []pair{{36, 20}, {58, 20}, {80, 20}}},
	{"constraint_specification_tests_for_priority_with_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexLegacy, 2, []pair{{0, 20}, {22, 20}, {44, 56}}},
	{"constraint_specification_tests_for_priority_with_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexLegacy, 2, []pair{{0, 20}, {22, 20}, {44, 56}}},
	{"constraint_specification_tests_for_priority_with_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceEvenly, 2, []pair{{10, 20}, {40, 20}, {70, 20}}},
	{"constraint_specification_tests_for_priority_with_spacing", []Constraint{Length(20), Length(20), Length(20)}, FlexSpaceAround, 2, []pair{{7, 20}, {40, 20}, {73, 20}}},
	{"flex_spacing_lower_priority_than_user_spacing", []Constraint{Length(10), Length(10)}, FlexCenter, 80, []pair{{0, 10}, {90, 10}}},
}

// spacerCases check the (x, width) of the gaps between segments, which widgets
// with collapsed borders draw into.
var spacerCases = []struct {
	name        string
	constraints []Constraint
	flex        Flex
	spacing     int
	expected    []pair
}{
	{"split_with_spacers_no_spacing", []Constraint{Length(10), Length(10)}, FlexLegacy, 0, []pair{{0, 0}, {10, 0}, {100, 0}}},
	{"split_with_spacers_no_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceBetween, 0, []pair{{0, 0}, {10, 80}, {100, 0}}},
	{"split_with_spacers_no_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceEvenly, 0, []pair{{0, 27}, {37, 26}, {73, 27}}},
	{"split_with_spacers_no_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceAround, 0, []pair{{0, 20}, {30, 40}, {80, 20}}},
	{"split_with_spacers_no_spacing", []Constraint{Length(10), Length(10)}, FlexStart, 0, []pair{{0, 0}, {10, 0}, {20, 80}}},
	{"split_with_spacers_no_spacing", []Constraint{Length(10), Length(10)}, FlexCenter, 0, []pair{{0, 40}, {50, 0}, {60, 40}}},
	{"split_with_spacers_no_spacing", []Constraint{Length(10), Length(10)}, FlexEnd, 0, []pair{{0, 80}, {90, 0}, {100, 0}}},
	{"split_with_spacers_and_spacing", []Constraint{Length(10), Length(10)}, FlexLegacy, 5, []pair{{0, 0}, {10, 5}, {100, 0}}},
	{"split_with_spacers_and_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceBetween, 5, []pair{{0, 0}, {10, 80}, {100, 0}}},
	{"split_with_spacers_and_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceEvenly, 5, []pair{{0, 27}, {37, 26}, {73, 27}}},
	{"split_with_spacers_and_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceAround, 5, []pair{{0, 20}, {30, 40}, {80, 20}}},
	{"split_with_spacers_and_spacing", []Constraint{Length(10), Length(10)}, FlexStart, 5, []pair{{0, 0}, {10, 5}, {25, 75}}},
	{"split_with_spacers_and_spacing", []Constraint{Length(10), Length(10)}, FlexCenter, 5, []pair{{0, 38}, {48, 5}, {63, 37}}},
	{"split_with_spacers_and_spacing", []Constraint{Length(10), Length(10)}, FlexEnd, 5, []pair{{0, 75}, {85, 5}, {100, 0}}},
	{"split_with_spacers_and_overlap", []Constraint{Length(10), Length(10)}, FlexLegacy, -1, []pair{{0, 0}, {10, 0}, {100, 0}}},
	{"split_with_spacers_and_overlap", []Constraint{Length(10), Length(10)}, FlexSpaceBetween, -1, []pair{{0, 0}, {10, 80}, {100, 0}}},
	{"split_with_spacers_and_overlap", []Constraint{Length(10), Length(10)}, FlexSpaceEvenly, -1, []pair{{0, 27}, {37, 26}, {73, 27}}},
	{"split_with_spacers_and_overlap", []Constraint{Length(10), Length(10)}, FlexSpaceAround, -1, []pair{{0, 20}, {30, 40}, {80, 20}}},
	{"split_with_spacers_and_overlap", []Constraint{Length(10), Length(10)}, FlexStart, -1, []pair{{0, 0}, {10, 0}, {19, 81}}},
	{"split_with_spacers_and_overlap", []Constraint{Length(10), Length(10)}, FlexCenter, -1, []pair{{0, 41}, {51, 0}, {60, 40}}},
	{"split_with_spacers_and_overlap", []Constraint{Length(10), Length(10)}, FlexEnd, -1, []pair{{0, 81}, {91, 0}, {100, 0}}},
	{"split_with_spacers_and_too_much_spacing", []Constraint{Length(10), Length(10)}, FlexLegacy, 200, []pair{{0, 0}, {0, 100}, {100, 0}}},
	{"split_with_spacers_and_too_much_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceBetween, 200, []pair{{0, 0}, {0, 100}, {100, 0}}},
	{"split_with_spacers_and_too_much_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceEvenly, 200, []pair{{0, 33}, {33, 34}, {67, 33}}},
	{"split_with_spacers_and_too_much_spacing", []Constraint{Length(10), Length(10)}, FlexSpaceAround, 200, []pair{{0, 25}, {25, 50}, {75, 25}}},
	{"split_with_spacers_and_too_much_spacing", []Constraint{Length(10), Length(10)}, FlexStart, 200, []pair{{0, 0}, {0, 100}, {100, 0}}},
	{"split_with_spacers_and_too_much_spacing", []Constraint{Length(10), Length(10)}, FlexCenter, 200, []pair{{0, 0}, {0, 100}, {100, 0}}},
	{"split_with_spacers_and_too_much_spacing", []Constraint{Length(10), Length(10)}, FlexEnd, 200, []pair{{0, 0}, {0, 100}, {100, 0}}},
}

// widthCases check only the widths, and must hold across every non-Legacy flex
// mode.
var widthCases = []struct {
	name        string
	constraints []Constraint
	expected    []uint16
}{
	{"length_is_higher_priority_in_flex", []Constraint{Min(25), Length(25), Max(25)}, []uint16{50, 25, 25}},
	{"length_is_higher_priority_in_flex", []Constraint{Max(25), Length(25), Min(25)}, []uint16{25, 25, 50}},
	{"length_is_higher_priority_in_flex", []Constraint{Length(33), Length(33), Length(33)}, []uint16{33, 33, 33}},
	{"length_is_higher_priority_in_flex", []Constraint{Length(25), Length(25), Length(25)}, []uint16{25, 25, 25}},
	{"length_is_higher_priority_in_flex", []Constraint{Percentage(25), Length(25), Ratio(1, 4)}, []uint16{25, 25, 25}},
	{"length_is_higher_priority_in_flex", []Constraint{Length(25), Ratio(1, 4), Percentage(25)}, []uint16{25, 25, 25}},
	{"length_is_higher_priority_in_flex", []Constraint{Ratio(1, 4), Length(25), Percentage(25)}, []uint16{25, 25, 25}},
	{"length_is_higher_priority_in_flex", []Constraint{Ratio(1, 4), Percentage(25), Length(25)}, []uint16{25, 25, 25}},
	{"length_is_higher_priority_in_flex", []Constraint{Length(100), Length(1), Min(20)}, []uint16{79, 1, 20}},
	{"length_is_higher_priority_in_flex", []Constraint{Min(20), Length(1), Length(100)}, []uint16{20, 1, 79}},
	{"length_is_higher_priority_in_flex", []Constraint{Fill(1), Length(10), Fill(1)}, []uint16{45, 10, 45}},
	{"length_is_higher_priority_in_flex", []Constraint{Fill(1), Length(10), Fill(2)}, []uint16{30, 10, 60}},
	{"length_is_higher_priority_in_flex", []Constraint{Fill(1), Length(10), Fill(4)}, []uint16{18, 10, 72}},
	{"length_is_higher_priority_in_flex", []Constraint{Fill(1), Length(10), Fill(5)}, []uint16{15, 10, 75}},
	{"length_is_higher_priority_in_flex", []Constraint{Length(25), Length(25), Length(25)}, []uint16{25, 25, 25}},
}
