// Code generated by tools/gen_palettes.py from
// ratatui-core/src/style/palette/tailwind.rs @ ratatui-v0.30.2. DO NOT EDIT.

// Package tailwind holds the Tailwind CSS colour palettes, as ratatui does.
//
// Each palette is a ramp of eleven shades of one hue, from C50 at the lightest
// to C950 at the darkest, chosen to work together. Terminal colours picked by
// hand rarely do:
//
//	style := catatui.NewStyle().
//		Fg(tailwind.Slate.C200).
//		Bg(tailwind.Blue.C900)
//
// These are 24-bit colours, so a terminal without true colour support will
// approximate them. Where that matters, keep an indexed fallback beside them.
package tailwind

import "github.com/Fiend3d/catatui"

// Palette is one hue in eleven shades, lightest first.
type Palette struct {
	C50  catatui.Color
	C100 catatui.Color
	C200 catatui.Color
	C300 catatui.Color
	C400 catatui.Color
	C500 catatui.Color
	C600 catatui.Color
	C700 catatui.Color
	C800 catatui.Color
	C900 catatui.Color
	C950 catatui.Color
}

// Black is included so that a design does not have to fall back on the
// terminal's own idea of it.
var Black = catatui.RgbFromU32(0x000000)

// White is included so that a design does not have to fall back on the
// terminal's own idea of it.
var White = catatui.RgbFromU32(0xffffff)

// Slate is the slate ramp.
var Slate = Palette{
	C50:  catatui.RgbFromU32(0xf8fafc),
	C100: catatui.RgbFromU32(0xf1f5f9),
	C200: catatui.RgbFromU32(0xe2e8f0),
	C300: catatui.RgbFromU32(0xcbd5e1),
	C400: catatui.RgbFromU32(0x94a3b8),
	C500: catatui.RgbFromU32(0x64748b),
	C600: catatui.RgbFromU32(0x475569),
	C700: catatui.RgbFromU32(0x334155),
	C800: catatui.RgbFromU32(0x1e293b),
	C900: catatui.RgbFromU32(0x0f172a),
	C950: catatui.RgbFromU32(0x020617),
}

// Gray is the gray ramp.
var Gray = Palette{
	C50:  catatui.RgbFromU32(0xf9fafb),
	C100: catatui.RgbFromU32(0xf3f4f6),
	C200: catatui.RgbFromU32(0xe5e7eb),
	C300: catatui.RgbFromU32(0xd1d5db),
	C400: catatui.RgbFromU32(0x9ca3af),
	C500: catatui.RgbFromU32(0x6b7280),
	C600: catatui.RgbFromU32(0x4b5563),
	C700: catatui.RgbFromU32(0x374151),
	C800: catatui.RgbFromU32(0x1f2937),
	C900: catatui.RgbFromU32(0x111827),
	C950: catatui.RgbFromU32(0x030712),
}

// Zinc is the zinc ramp.
var Zinc = Palette{
	C50:  catatui.RgbFromU32(0xfafafa),
	C100: catatui.RgbFromU32(0xf4f4f5),
	C200: catatui.RgbFromU32(0xe4e4e7),
	C300: catatui.RgbFromU32(0xd4d4d8),
	C400: catatui.RgbFromU32(0xa1a1aa),
	C500: catatui.RgbFromU32(0x71717a),
	C600: catatui.RgbFromU32(0x52525b),
	C700: catatui.RgbFromU32(0x3f3f46),
	C800: catatui.RgbFromU32(0x27272a),
	C900: catatui.RgbFromU32(0x18181b),
	C950: catatui.RgbFromU32(0x09090b),
}

// Neutral is the neutral ramp.
var Neutral = Palette{
	C50:  catatui.RgbFromU32(0xfafafa),
	C100: catatui.RgbFromU32(0xf5f5f5),
	C200: catatui.RgbFromU32(0xe5e5e5),
	C300: catatui.RgbFromU32(0xd4d4d4),
	C400: catatui.RgbFromU32(0xa3a3a3),
	C500: catatui.RgbFromU32(0x737373),
	C600: catatui.RgbFromU32(0x525252),
	C700: catatui.RgbFromU32(0x404040),
	C800: catatui.RgbFromU32(0x262626),
	C900: catatui.RgbFromU32(0x171717),
	C950: catatui.RgbFromU32(0x0a0a0a),
}

// Stone is the stone ramp.
var Stone = Palette{
	C50:  catatui.RgbFromU32(0xfafaf9),
	C100: catatui.RgbFromU32(0xf5f5f4),
	C200: catatui.RgbFromU32(0xe7e5e4),
	C300: catatui.RgbFromU32(0xd6d3d1),
	C400: catatui.RgbFromU32(0xa8a29e),
	C500: catatui.RgbFromU32(0x78716c),
	C600: catatui.RgbFromU32(0x57534e),
	C700: catatui.RgbFromU32(0x44403c),
	C800: catatui.RgbFromU32(0x292524),
	C900: catatui.RgbFromU32(0x1c1917),
	C950: catatui.RgbFromU32(0x0c0a09),
}

// Red is the red ramp.
var Red = Palette{
	C50:  catatui.RgbFromU32(0xfef2f2),
	C100: catatui.RgbFromU32(0xfee2e2),
	C200: catatui.RgbFromU32(0xfecaca),
	C300: catatui.RgbFromU32(0xfca5a5),
	C400: catatui.RgbFromU32(0xf87171),
	C500: catatui.RgbFromU32(0xef4444),
	C600: catatui.RgbFromU32(0xdc2626),
	C700: catatui.RgbFromU32(0xb91c1c),
	C800: catatui.RgbFromU32(0x991b1b),
	C900: catatui.RgbFromU32(0x7f1d1d),
	C950: catatui.RgbFromU32(0x450a0a),
}

// Orange is the orange ramp.
var Orange = Palette{
	C50:  catatui.RgbFromU32(0xfff7ed),
	C100: catatui.RgbFromU32(0xffedd5),
	C200: catatui.RgbFromU32(0xfed7aa),
	C300: catatui.RgbFromU32(0xfdba74),
	C400: catatui.RgbFromU32(0xfb923c),
	C500: catatui.RgbFromU32(0xf97316),
	C600: catatui.RgbFromU32(0xea580c),
	C700: catatui.RgbFromU32(0xc2410c),
	C800: catatui.RgbFromU32(0x9a3412),
	C900: catatui.RgbFromU32(0x7c2d12),
	C950: catatui.RgbFromU32(0x431407),
}

// Amber is the amber ramp.
var Amber = Palette{
	C50:  catatui.RgbFromU32(0xfffbeb),
	C100: catatui.RgbFromU32(0xfef3c7),
	C200: catatui.RgbFromU32(0xfde68a),
	C300: catatui.RgbFromU32(0xfcd34d),
	C400: catatui.RgbFromU32(0xfbbf24),
	C500: catatui.RgbFromU32(0xf59e0b),
	C600: catatui.RgbFromU32(0xd97706),
	C700: catatui.RgbFromU32(0xb45309),
	C800: catatui.RgbFromU32(0x92400e),
	C900: catatui.RgbFromU32(0x78350f),
	C950: catatui.RgbFromU32(0x451a03),
}

// Yellow is the yellow ramp.
var Yellow = Palette{
	C50:  catatui.RgbFromU32(0xfefce8),
	C100: catatui.RgbFromU32(0xfef9c3),
	C200: catatui.RgbFromU32(0xfef08a),
	C300: catatui.RgbFromU32(0xfde047),
	C400: catatui.RgbFromU32(0xfacc15),
	C500: catatui.RgbFromU32(0xeab308),
	C600: catatui.RgbFromU32(0xca8a04),
	C700: catatui.RgbFromU32(0xa16207),
	C800: catatui.RgbFromU32(0x854d0e),
	C900: catatui.RgbFromU32(0x713f12),
	C950: catatui.RgbFromU32(0x422006),
}

// Lime is the lime ramp.
var Lime = Palette{
	C50:  catatui.RgbFromU32(0xf7fee7),
	C100: catatui.RgbFromU32(0xecfccb),
	C200: catatui.RgbFromU32(0xd9f99d),
	C300: catatui.RgbFromU32(0xbef264),
	C400: catatui.RgbFromU32(0xa3e635),
	C500: catatui.RgbFromU32(0x84cc16),
	C600: catatui.RgbFromU32(0x65a30d),
	C700: catatui.RgbFromU32(0x4d7c0f),
	C800: catatui.RgbFromU32(0x3f6212),
	C900: catatui.RgbFromU32(0x365314),
	C950: catatui.RgbFromU32(0x1a2e05),
}

// Green is the green ramp.
var Green = Palette{
	C50:  catatui.RgbFromU32(0xf0fdf4),
	C100: catatui.RgbFromU32(0xdcfce7),
	C200: catatui.RgbFromU32(0xbbf7d0),
	C300: catatui.RgbFromU32(0x86efac),
	C400: catatui.RgbFromU32(0x4ade80),
	C500: catatui.RgbFromU32(0x22c55e),
	C600: catatui.RgbFromU32(0x16a34a),
	C700: catatui.RgbFromU32(0x15803d),
	C800: catatui.RgbFromU32(0x166534),
	C900: catatui.RgbFromU32(0x14532d),
	C950: catatui.RgbFromU32(0x052e16),
}

// Emerald is the emerald ramp.
var Emerald = Palette{
	C50:  catatui.RgbFromU32(0xecfdf5),
	C100: catatui.RgbFromU32(0xd1fae5),
	C200: catatui.RgbFromU32(0xa7f3d0),
	C300: catatui.RgbFromU32(0x6ee7b7),
	C400: catatui.RgbFromU32(0x34d399),
	C500: catatui.RgbFromU32(0x10b981),
	C600: catatui.RgbFromU32(0x059669),
	C700: catatui.RgbFromU32(0x047857),
	C800: catatui.RgbFromU32(0x065f46),
	C900: catatui.RgbFromU32(0x064e3b),
	C950: catatui.RgbFromU32(0x022c22),
}

// Teal is the teal ramp.
var Teal = Palette{
	C50:  catatui.RgbFromU32(0xf0fdfa),
	C100: catatui.RgbFromU32(0xccfbf1),
	C200: catatui.RgbFromU32(0x99f6e4),
	C300: catatui.RgbFromU32(0x5eead4),
	C400: catatui.RgbFromU32(0x2dd4bf),
	C500: catatui.RgbFromU32(0x14b8a6),
	C600: catatui.RgbFromU32(0x0d9488),
	C700: catatui.RgbFromU32(0x0f766e),
	C800: catatui.RgbFromU32(0x115e59),
	C900: catatui.RgbFromU32(0x134e4a),
	C950: catatui.RgbFromU32(0x042f2e),
}

// Cyan is the cyan ramp.
var Cyan = Palette{
	C50:  catatui.RgbFromU32(0xecfeff),
	C100: catatui.RgbFromU32(0xcffafe),
	C200: catatui.RgbFromU32(0xa5f3fc),
	C300: catatui.RgbFromU32(0x67e8f9),
	C400: catatui.RgbFromU32(0x22d3ee),
	C500: catatui.RgbFromU32(0x06b6d4),
	C600: catatui.RgbFromU32(0x0891b2),
	C700: catatui.RgbFromU32(0x0e7490),
	C800: catatui.RgbFromU32(0x155e75),
	C900: catatui.RgbFromU32(0x164e63),
	C950: catatui.RgbFromU32(0x083344),
}

// Sky is the sky ramp.
var Sky = Palette{
	C50:  catatui.RgbFromU32(0xf0f9ff),
	C100: catatui.RgbFromU32(0xe0f2fe),
	C200: catatui.RgbFromU32(0xbae6fd),
	C300: catatui.RgbFromU32(0x7dd3fc),
	C400: catatui.RgbFromU32(0x38bdf8),
	C500: catatui.RgbFromU32(0x0ea5e9),
	C600: catatui.RgbFromU32(0x0284c7),
	C700: catatui.RgbFromU32(0x0369a1),
	C800: catatui.RgbFromU32(0x075985),
	C900: catatui.RgbFromU32(0x0c4a6e),
	C950: catatui.RgbFromU32(0x082f49),
}

// Blue is the blue ramp.
var Blue = Palette{
	C50:  catatui.RgbFromU32(0xeff6ff),
	C100: catatui.RgbFromU32(0xdbeafe),
	C200: catatui.RgbFromU32(0xbfdbfe),
	C300: catatui.RgbFromU32(0x93c5fd),
	C400: catatui.RgbFromU32(0x60a5fa),
	C500: catatui.RgbFromU32(0x3b82f6),
	C600: catatui.RgbFromU32(0x2563eb),
	C700: catatui.RgbFromU32(0x1d4ed8),
	C800: catatui.RgbFromU32(0x1e40af),
	C900: catatui.RgbFromU32(0x1e3a8a),
	C950: catatui.RgbFromU32(0x172554),
}

// Indigo is the indigo ramp.
var Indigo = Palette{
	C50:  catatui.RgbFromU32(0xeef2ff),
	C100: catatui.RgbFromU32(0xe0e7ff),
	C200: catatui.RgbFromU32(0xc7d2fe),
	C300: catatui.RgbFromU32(0xa5b4fc),
	C400: catatui.RgbFromU32(0x818cf8),
	C500: catatui.RgbFromU32(0x6366f1),
	C600: catatui.RgbFromU32(0x4f46e5),
	C700: catatui.RgbFromU32(0x4338ca),
	C800: catatui.RgbFromU32(0x3730a3),
	C900: catatui.RgbFromU32(0x312e81),
	C950: catatui.RgbFromU32(0x1e1b4b),
}

// Violet is the violet ramp.
var Violet = Palette{
	C50:  catatui.RgbFromU32(0xf5f3ff),
	C100: catatui.RgbFromU32(0xede9fe),
	C200: catatui.RgbFromU32(0xddd6fe),
	C300: catatui.RgbFromU32(0xc4b5fd),
	C400: catatui.RgbFromU32(0xa78bfa),
	C500: catatui.RgbFromU32(0x8b5cf6),
	C600: catatui.RgbFromU32(0x7c3aed),
	C700: catatui.RgbFromU32(0x6d28d9),
	C800: catatui.RgbFromU32(0x5b21b6),
	C900: catatui.RgbFromU32(0x4c1d95),
	C950: catatui.RgbFromU32(0x2e1065),
}

// Purple is the purple ramp.
var Purple = Palette{
	C50:  catatui.RgbFromU32(0xfaf5ff),
	C100: catatui.RgbFromU32(0xf3e8ff),
	C200: catatui.RgbFromU32(0xe9d5ff),
	C300: catatui.RgbFromU32(0xd8b4fe),
	C400: catatui.RgbFromU32(0xc084fc),
	C500: catatui.RgbFromU32(0xa855f7),
	C600: catatui.RgbFromU32(0x9333ea),
	C700: catatui.RgbFromU32(0x7e22ce),
	C800: catatui.RgbFromU32(0x6b21a8),
	C900: catatui.RgbFromU32(0x581c87),
	C950: catatui.RgbFromU32(0x3b0764),
}

// Fuchsia is the fuchsia ramp.
var Fuchsia = Palette{
	C50:  catatui.RgbFromU32(0xfdf4ff),
	C100: catatui.RgbFromU32(0xfae8ff),
	C200: catatui.RgbFromU32(0xf5d0fe),
	C300: catatui.RgbFromU32(0xf0abfc),
	C400: catatui.RgbFromU32(0xe879f9),
	C500: catatui.RgbFromU32(0xd946ef),
	C600: catatui.RgbFromU32(0xc026d3),
	C700: catatui.RgbFromU32(0xa21caf),
	C800: catatui.RgbFromU32(0x86198f),
	C900: catatui.RgbFromU32(0x701a75),
	C950: catatui.RgbFromU32(0x4a044e),
}

// Pink is the pink ramp.
var Pink = Palette{
	C50:  catatui.RgbFromU32(0xfdf2f8),
	C100: catatui.RgbFromU32(0xfce7f3),
	C200: catatui.RgbFromU32(0xfbcfe8),
	C300: catatui.RgbFromU32(0xf9a8d4),
	C400: catatui.RgbFromU32(0xf472b6),
	C500: catatui.RgbFromU32(0xec4899),
	C600: catatui.RgbFromU32(0xdb2777),
	C700: catatui.RgbFromU32(0xbe185d),
	C800: catatui.RgbFromU32(0x9d174d),
	C900: catatui.RgbFromU32(0x831843),
	C950: catatui.RgbFromU32(0x500724),
}

// Rose is the rose ramp.
var Rose = Palette{
	C50:  catatui.RgbFromU32(0xfff1f2),
	C100: catatui.RgbFromU32(0xffe4e6),
	C200: catatui.RgbFromU32(0xfecdd3),
	C300: catatui.RgbFromU32(0xfda4af),
	C400: catatui.RgbFromU32(0xfb7185),
	C500: catatui.RgbFromU32(0xf43f5e),
	C600: catatui.RgbFromU32(0xe11d48),
	C700: catatui.RgbFromU32(0xbe123c),
	C800: catatui.RgbFromU32(0x9f1239),
	C900: catatui.RgbFromU32(0x881337),
	C950: catatui.RgbFromU32(0x4c0519),
}
