#!/usr/bin/env python3
"""Generate the colormap tables for the volatility-surface example.

ratatui's volatility-surface reaches for the colorgrad crate to get viridis,
plasma and inferno. catatui has no such dependency and does not want one for a
single example, so the three tables are written out instead. They are 256
hardcoded colours each with no logic in them, which is the same case as the
tailwind palettes: translated mechanically rather than by hand.

colorgrad takes the tables from matplotlib, so this reads them from matplotlib
directly:

    python tools/gen_colormaps.py
    gofmt -w examples/apps/volatility-surface/colormaps.go

Requires matplotlib. Writes:
    examples/apps/volatility-surface/colormaps.go
"""

import os
import sys

try:
    import matplotlib
except ImportError:
    sys.exit("gen_colormaps.py needs matplotlib: pip install matplotlib")

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(REPO, "examples", "apps", "volatility-surface", "colormaps.go")

# The maps colorgrad's preset module carries, and this example cycles through.
COLORMAPS = ["viridis", "plasma", "inferno"]

HEADER = '''// Code generated by tools/gen_colormaps.py from matplotlib's colormap data.
// DO NOT EDIT.

package main

// The three perceptually uniform colormaps, 256 stops each as 0xRRGGBB.
//
// ratatui's example gets these from the colorgrad crate, which takes them from
// matplotlib, which is where these are read from. Their designers — Nathaniel
// J. Smith, Stefan van der Walt and Eric Firing — placed them in the public
// domain, so they travel without a licence of their own.
//
// "Perceptually uniform" means equal steps along the map look like equal steps
// in brightness, which is what makes a surface drawn in one of them readable as
// a height rather than as a pattern. A rainbow ramp does not have that property
// and invents ridges that are not in the data.
'''


def table(name):
    """Return the Go declaration of one colormap as 256 packed RGB values."""
    colors = matplotlib.colormaps[name].colors
    if len(colors) != 256:
        sys.exit("%s has %d stops, expected 256" % (name, len(colors)))

    values = []
    for r, g, b in colors:
        values.append(
            (round(r * 255) << 16) | (round(g * 255) << 8) | round(b * 255)
        )

    lines = ["// %sStops is matplotlib's %s." % (name, name),
             "var %sStops = [256]uint32{" % name]
    for start in range(0, 256, 8):
        row = values[start:start + 8]
        lines.append("\t" + " ".join("0x%06x," % value for value in row))
    lines.append("}")
    return "\n".join(lines)


def main():
    out = [HEADER] + [table(name) for name in COLORMAPS]
    with open(OUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n\n".join(out) + "\n")
    print("wrote %s" % os.path.relpath(OUT, REPO))


if __name__ == "__main__":
    main()
