#!/usr/bin/env python3
"""Generate the tailwind and material colour palettes from ratatui's sources.

The palettes are several hundred hardcoded RGB values with no logic in them, so
they are translated mechanically rather than by hand, the same way the layout
cases are. Run this against a `_ref/ratatui` checkout:

    python tools/gen_palettes.py
    gofmt -w palette/tailwind/tailwind.go palette/material/material.go

Reads:
    _ref/ratatui/ratatui-core/src/style/palette/tailwind.rs
    _ref/ratatui/ratatui-core/src/style/palette/material.rs
"""

import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REF = os.path.join(REPO, "_ref", "ratatui", "ratatui-core", "src", "style", "palette")

# Rust names each shade c50..c950; Go exports them as C50..C950.
TAILWIND_SHADES = ["c50", "c100", "c200", "c300", "c400", "c500",
                   "c600", "c700", "c800", "c900", "c950"]
MATERIAL_SHADES = ["c50", "c100", "c200", "c300", "c400", "c500",
                   "c600", "c700", "c800", "c900"]
MATERIAL_ACCENTS = ["a100", "a200", "a400", "a700"]


def go_name(rust_name):
    """SLATE -> Slate, DEEP_PURPLE -> DeepPurple."""
    return "".join(part.capitalize() for part in rust_name.split("_"))


def read(name):
    with open(os.path.join(REF, name), encoding="utf-8") as f:
        return f.read()


def parse_tailwind():
    """Return (palettes, singles) from tailwind.rs.

    palettes is [(NAME, [11 hex values])], singles is [(NAME, hex)].
    """
    source = read("tailwind.rs")
    palettes = []
    for match in re.finditer(
        r"^pub const (\w+): Palette = Palette \{(.*?)^\};", source, re.M | re.S
    ):
        name, body = match.group(1), match.group(2)
        values = dict(re.findall(r"(c\d+): Color::from_u32\((0x[0-9a-fA-F]+)\)", body))
        palettes.append((name, [values[shade] for shade in TAILWIND_SHADES]))

    singles = re.findall(r"^pub const (\w+): Color = Color::from_u32\((0x[0-9a-fA-F]+)\);",
                         source, re.M)
    return palettes, singles


def parse_material():
    """Return (accented, non_accented, singles) from material.rs.

    The palettes are built from arrays in a private `variants` module, so the
    arrays are read and the constants are matched to them by name.
    """
    source = read("material.rs")

    variants = {}
    for match in re.finditer(
        r"pub const (\w+): \[u32; \d+\] = \[(.*?)\];", source, re.S
    ):
        name, body = match.group(1), match.group(2)
        variants[name] = re.findall(r"0x[0-9a-fA-F]+", body)

    accented, non_accented = [], []
    for match in re.finditer(
        r"^pub const (\w+): (AccentedPalette|NonAccentedPalette) = "
        r"\w+::from_variants\(variants::(\w+)\);",
        source, re.M
    ):
        name, kind, variant = match.group(1), match.group(2), match.group(3)
        values = variants[variant]
        if kind == "AccentedPalette":
            accented.append((name, values))
        else:
            non_accented.append((name, values))

    singles = re.findall(r"^pub const (\w+): Color = Color::from_u32\((0x[0-9a-fA-F]+)\);",
                         source, re.M)
    return accented, non_accented, singles


def color(value):
    return "catatui.RgbFromU32(%s)" % value.lower()


def palette_var(name, kind, fields, values, comment):
    lines = ["// %s is %s." % (go_name(name), comment),
             "var %s = %s{" % (go_name(name), kind)]
    for field, value in zip(fields, values):
        lines.append("\t%s: %s," % (field.upper(), color(value)))
    lines.append("}")
    return "\n".join(lines)


def gen_tailwind():
    palettes, singles = parse_tailwind()
    out = ['''// Code generated by tools/gen_palettes.py from
// ratatui-core/src/style/palette/tailwind.rs @ ratatui-v0.30.2. DO NOT EDIT.

// Package tailwind holds the Tailwind CSS colour palettes, as ratatui does.
//
// Each palette is a ramp of eleven shades of one hue, from C50 at the lightest
// to C950 at the darkest, chosen to work together. Terminal colours picked by
// hand rarely do:
//
//\tstyle := catatui.NewStyle().
//\t\tFg(tailwind.Slate.C200).
//\t\tBg(tailwind.Blue.C900)
//
// These are 24-bit colours, so a terminal without true colour support will
// approximate them. Where that matters, keep an indexed fallback beside them.
package tailwind

import "github.com/Fiend3d/catatui"

// Palette is one hue in eleven shades, lightest first.
type Palette struct {
\tC50  catatui.Color
\tC100 catatui.Color
\tC200 catatui.Color
\tC300 catatui.Color
\tC400 catatui.Color
\tC500 catatui.Color
\tC600 catatui.Color
\tC700 catatui.Color
\tC800 catatui.Color
\tC900 catatui.Color
\tC950 catatui.Color
}''']

    for name, value in singles:
        out.append("// %s is included so that a design does not have to fall back on the\n"
                   "// terminal's own idea of it.\nvar %s = %s"
                   % (go_name(name), go_name(name), color(value)))

    for name, values in palettes:
        out.append(palette_var(name, "Palette", TAILWIND_SHADES, values,
                               "the %s ramp" % name.lower().replace("_", " ")))
    return "\n\n".join(out) + "\n"


def gen_material():
    accented, non_accented, singles = parse_material()
    out = ['''// Code generated by tools/gen_palettes.py from
// ratatui-core/src/style/palette/material.rs @ ratatui-v0.30.2. DO NOT EDIT.

// Package material holds Google's 2014 Material design colour palettes, as
// ratatui does.
//
// Each palette is a ramp of ten shades of one hue, from C50 at the lightest to
// C900 at the darkest. Most also carry four accent colours, A100 to A700, which
// are brighter than the ramp and meant for the one thing on screen that should
// catch the eye:
//
//\tstyle := catatui.NewStyle().
//\t\tFg(material.Indigo.A200).
//\t\tBg(material.BlueGray.C900)
//
// These are 24-bit colours, so a terminal without true colour support will
// approximate them.
package material

import "github.com/Fiend3d/catatui"

// Palette is one hue in ten shades, lightest first.
type Palette struct {
\tC50  catatui.Color
\tC100 catatui.Color
\tC200 catatui.Color
\tC300 catatui.Color
\tC400 catatui.Color
\tC500 catatui.Color
\tC600 catatui.Color
\tC700 catatui.Color
\tC800 catatui.Color
\tC900 catatui.Color
}

// AccentedPalette is a Palette with four accent colours beside it.
type AccentedPalette struct {
\tC50  catatui.Color
\tC100 catatui.Color
\tC200 catatui.Color
\tC300 catatui.Color
\tC400 catatui.Color
\tC500 catatui.Color
\tC600 catatui.Color
\tC700 catatui.Color
\tC800 catatui.Color
\tC900 catatui.Color
\tA100 catatui.Color
\tA200 catatui.Color
\tA400 catatui.Color
\tA700 catatui.Color
}''']

    for name, value in singles:
        out.append("// %s is included so that a design does not have to fall back on the\n"
                   "// terminal's own idea of it.\nvar %s = %s"
                   % (go_name(name), go_name(name), color(value)))

    for name, values in accented:
        out.append(palette_var(name, "AccentedPalette",
                               MATERIAL_SHADES + MATERIAL_ACCENTS, values,
                               "the %s ramp, with accents" % name.lower().replace("_", " ")))
    for name, values in non_accented:
        out.append(palette_var(name, "Palette", MATERIAL_SHADES, values,
                               "the %s ramp" % name.lower().replace("_", " ")))
    return "\n\n".join(out) + "\n"


def write(path, content):
    full = os.path.join(REPO, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8", newline="\n") as f:
        f.write(content)
    print("wrote", path)


def main():
    if not os.path.isdir(REF):
        raise SystemExit(
            "no _ref/ratatui checkout: see the Development section of the README"
        )
    write("palette/tailwind/tailwind.go", gen_tailwind())
    write("palette/material/material.go", gen_material())
    return 0


if __name__ == "__main__":
    sys.exit(main())
